language: python
python:
  - "3.7"
install:
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - python manage.py test
  - coverage run --source=. manage.py test
after_success:
  - coveralls
