# Generated by Django 3.1.3 on 2020-11-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201114_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='slugs',
            field=models.SlugField(default=''),
        ),
    ]
