# Generated by Django 3.1.3 on 2020-11-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_entry_slugs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='slugs',
            new_name='slug',
        ),
    ]
